In [9]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd
import tensorflow as tf
import MIDASpy as md

In [10]:
column_names=['Column 1','Column 2','Column 3','Column 4','Column 5','Column 6','Column 7','Column 8','Column 9','Column 10','Column 11','Column 12','Column 13','Column 14','Column 15','Column 16','Column 17','Column 18','Column 19','Column 20','Column 21','Column 22']
df=pd.read_excel(r'C:\Users\furqz\OneDrive\Desktop\Data mining stiff\incomplete\Incomplete Datasets Without Labels\MUSH\MUSH_AN_1.xlsx',header=None,names=column_names)
df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,NaN,p,f,c,n,n,e,...,NaN,NaN,NaN,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [11]:
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [12]:
import tensorflow as tf
tf.compat.v1.reset_default_graph()

In [13]:
import tensorflow as tf
tf.compat.v1.reset_default_graph()

In [14]:
import tensorflow.compat.v1 as tf
tf.reset_default_graph()

In [15]:
categorical = ['Column 1','Column 2','Column 3','Column 4','Column 5','Column 6','Column 7','Column 8','Column 9','Column 10','Column 11','Column 12','Column 13','Column 14','Column 15','Column 16','Column 17','Column 18','Column 19','Column 20','Column 21','Column 22']
data_cat, cat_cols_list = md.cat_conv(df[categorical])

df.drop(categorical, axis = 1, inplace = True)
constructor_list = [df]
constructor_list.append(data_cat)
data_in = pd.concat(constructor_list, axis=1)

na_loc = data_in.isnull()
data_in[na_loc] = np.nan

In [16]:
print(data_in.head())

   Column 1_b  Column 1_c  Column 1_f  Column 1_k  Column 1_s  Column 1_x  \
0         0.0         0.0         0.0         0.0         0.0         1.0
1         0.0         0.0         0.0         0.0         0.0         1.0
2         1.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         1.0
4         0.0         0.0         0.0         0.0         0.0         1.0

   Column 2_f  Column 2_g  Column 2_s  Column 2_y  ...  Column 21_n  \
0         0.0         0.0         1.0         0.0  ...          0.0
1         0.0         0.0         1.0         0.0  ...          1.0
2         0.0         0.0         1.0         0.0  ...          1.0
3         0.0         0.0         0.0         1.0  ...          0.0
4         0.0         0.0         1.0         0.0  ...          0.0

   Column 21_s  Column 21_v  Column 21_y  Column 22_d  Column 22_g  \
0          1.0          0.0          0.0          0.0          0.0
1          0.0          0.0          0.0          0.0          1.0
2          0.0          0.0          0.0          0.0          0.0
3          1.0          0.0          0.0          0.0          0.0
4          0.0          0.0          0.0          0.0          1.0

   Column 22_l  Column 22_m  Column 22_p  Column 22_u
0          0.0          0.0          0.0          1.0
1          0.0          0.0          0.0          0.0
2          0.0          1.0          0.0          0.0
3          0.0          0.0          0.0          1.0
4          0.0          0.0          0.0          0.0

[5 rows x 98 columns]

In [17]:
imputer = md.Midas(layer_structure = [22,22+30,22+30+30,22+30+30+30,22+30+30,22+30,22], vae_layer = False, seed = 100, input_drop = 0.5)
imputer.build_model(data_in,softmax_columns = cat_cols_list)
imputer.train_model(training_epochs = 100)

Size index: [6, 4, 8, 2, 7, 2, 2, 2, 9, 2, 4, 4, 4, 7, 7, 1, 2, 3, 4, 6, 6, 6]

Computation graph constructed

Model initialised

Epoch: 0 , loss: 26.71934691884301
Epoch: 1 , loss: 21.347454493696038
Epoch: 2 , loss: 20.676172998818483
Epoch: 3 , loss: 20.290382249788806
Epoch: 4 , loss: 19.995031665671956
Epoch: 5 , loss: 19.813218533992767
Epoch: 6 , loss: 19.67630877819928
Epoch: 7 , loss: 19.56085599281571
Epoch: 8 , loss: 19.365140774033286
Epoch: 9 , loss: 19.18104189092463
Epoch: 10 , loss: 19.0594213523648
Epoch: 11 , loss: 18.86494369940324
Epoch: 12 , loss: 18.799540013074875
Epoch: 13 , loss: 18.620962224223398
Epoch: 14 , loss: 18.56810389052738
Epoch: 15 , loss: 18.40043719248338
Epoch: 16 , loss: 18.327116562561557
Epoch: 17 , loss: 18.17858170650222
Epoch: 18 , loss: 18.11427171121944
Epoch: 19 , loss: 18.05523890527812
Epoch: 20 , loss: 17.825017861344598
Epoch: 21 , loss: 17.678905432874505
Epoch: 22 , loss: 17.543023415587164
Epoch: 23 , loss: 17.47542729973793
Epoch: 24 , loss: 17.41961958733472
Epoch: 25 , loss: 17.34735429828817
Epoch: 26 , loss: 17.29783181710677
Epoch: 27 , loss: 17.259452443231236
Epoch: 28 , loss: 17.16629326072606
Epoch: 29 , loss: 17.078698028217662
Epoch: 30 , loss: 16.9758721454577
Epoch: 31 , loss: 16.864897681908175
Epoch: 32 , loss: 16.691345217553053
Epoch: 33 , loss: 16.620486999099906
Epoch: 34 , loss: 16.500138066031717
Epoch: 35 , loss: 16.454354711554267
Epoch: 36 , loss: 16.304491834207013
Epoch: 37 , loss: 16.23462137579918
Epoch: 38 , loss: 16.13263591853055
Epoch: 39 , loss: 15.980883213606747
Epoch: 40 , loss: 15.881905301050706
Epoch: 41 , loss: 15.869963423772292
Epoch: 42 , loss: 15.784952851859005
Epoch: 43 , loss: 15.787553267045455
Epoch: 44 , loss: 15.83018352768638
Epoch: 45 , loss: 15.773114881732248
Epoch: 46 , loss: 15.714499457315965
Epoch: 47 , loss: 15.68455508351326
Epoch: 48 , loss: 15.630071688782085
Epoch: 49 , loss: 15.67089662768624
Epoch: 50 , loss: 15.682829770174893
Epoch: 51 , loss: 15.733383858745748
Epoch: 52 , loss: 15.64070424708453
Epoch: 53 , loss: 15.638022620569576
Epoch: 54 , loss: 15.597214934500782
Epoch: 55 , loss: 15.672713894735683
Epoch: 56 , loss: 15.67816123637286
Epoch: 57 , loss: 15.588234622370113
Epoch: 58 , loss: 15.613729430870576
Epoch: 59 , loss: 15.659917931665074
Epoch: 60 , loss: 15.641217036680741
Epoch: 61 , loss: 15.683379468592731
Epoch: 62 , loss: 15.64244459433989
Epoch: 63 , loss: 15.609779290177606
Epoch: 64 , loss: 15.571493601257151
Epoch: 65 , loss: 15.554539810527455
Epoch: 66 , loss: 15.578832553191619
Epoch: 67 , loss: 15.599346001039851
Epoch: 68 , loss: 15.544793895699762
Epoch: 69 , loss: 15.481796102090316
Epoch: 70 , loss: 15.468378980051387
Epoch: 71 , loss: 15.489579620686444
Epoch: 72 , loss: 15.434967750852758
Epoch: 73 , loss: 15.295722999356009
Epoch: 74 , loss: 15.32108175483617
Epoch: 75 , loss: 15.318353764035486
Epoch: 76 , loss: 15.194688493555242
Epoch: 77 , loss: 15.217273858460514
Epoch: 78 , loss: 15.113940488208424
Epoch: 79 , loss: 15.114544762806458
Epoch: 80 , loss: 15.225405208089136
Epoch: 81 , loss: 15.149879962205887
Epoch: 82 , loss: 15.137464818629352
Epoch: 83 , loss: 15.23864205587994
Epoch: 84 , loss: 15.050540360537441
Epoch: 85 , loss: 15.123146818442779
Epoch: 86 , loss: 15.09590722214092
Epoch: 87 , loss: 15.153944725340063
Epoch: 88 , loss: 15.024105814370243
Epoch: 89 , loss: 14.91196671128273
Epoch: 90 , loss: 15.012737959623337
Epoch: 91 , loss: 15.022002829746766
Epoch: 92 , loss: 15.01950124447996
Epoch: 93 , loss: 15.000001698732376
Epoch: 94 , loss: 14.967403493144296
Epoch: 95 , loss: 15.01095508445393
Epoch: 96 , loss: 14.971448643641038
Epoch: 97 , loss: 14.940449289300226
Epoch: 98 , loss: 14.919541442936117
Epoch: 99 , loss: 15.079044420610774
Training complete. Saving file...
Model saved in file: tmp/MIDAS

In [18]:
imputations = imputer.generate_samples(m=10).output_list

INFO:tensorflow:Restoring parameters from tmp/MIDAS
Model restored.

In [19]:
np.shape(imputations[-1])

(5644, 98)

In [20]:
new_df=imputations[-1]

In [21]:
complete_df=pd.read_excel(r'C:\Users\furqz\OneDrive\Desktop\Data mining stiff\complete\Original Datasets Without Labels\MUSH.xlsx',header=None,names=column_names)
complete_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [22]:
flat_cats = [cat for variable in cat_cols_list for cat in variable]

for i in range(len(imputations)):
    tmp_cat = [imputations[i][x].idxmax(axis=1) for x in cat_cols_list]
    cat_df = pd.DataFrame({categorical[i]:tmp_cat[i] for i in range(len(categorical))})
    imputations[i] = pd.concat([imputations[i], cat_df], axis = 1).drop(flat_cats, axis = 1)

In [23]:
print(imputations[-1].columns)

Index(['Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5', 'Column 6',
       'Column 7', 'Column 8', 'Column 9', 'Column 10', 'Column 11',
       'Column 12', 'Column 13', 'Column 14', 'Column 15', 'Column 16',
       'Column 17', 'Column 18', 'Column 19', 'Column 20', 'Column 21',
       'Column 22'],
      dtype='object')

In [24]:
new_df=imputations[-1]
new_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,Column 1_x,Column 2_s,Column 3_n,Column 4_t,Column 5_p,Column 6_f,Column 7_c,Column 8_n,Column 9_k,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_k,Column 21_s,Column 22_u
1,Column 1_x,Column 2_s,Column 3_y,Column 4_t,Column 5_a,Column 6_f,Column 7_c,Column 8_b,Column 9_k,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_n,Column 21_n,Column 22_g
2,Column 1_b,Column 2_s,Column 3_w,Column 4_t,Column 5_l,Column 6_f,Column 7_c,Column 8_b,Column 9_n,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_n,Column 21_n,Column 22_m
3,Column 1_x,Column 2_y,Column 3_w,Column 4_f,Column 5_p,Column 6_f,Column 7_c,Column 8_n,Column 9_n,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_k,Column 21_s,Column 22_u
4,Column 1_x,Column 2_s,Column 3_g,Column 4_f,Column 5_n,Column 6_f,Column 7_w,Column 8_b,Column 9_k,Column 10_t,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_e,Column 20_n,Column 21_a,Column 22_g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,Column 1_b,Column 2_y,Column 3_n,Column 4_f,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_y,Column 14_n,Column 15_n,Column 16_p,Column 17_w,Column 18_t,Column 19_p,Column 20_w,Column 21_y,Column 22_p
5640,Column 1_x,Column 2_y,Column 3_n,Column 4_f,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_y,Column 14_n,Column 15_n,Column 16_p,Column 17_w,Column 18_t,Column 19_p,Column 20_w,Column 21_y,Column 22_p
5641,Column 1_x,Column 2_y,Column 3_g,Column 4_t,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_t,Column 19_p,Column 20_w,Column 21_y,Column 22_p
5642,Column 1_x,Column 2_y,Column 3_c,Column 4_f,Column 5_m,Column 6_f,Column 7_c,Column 8_b,Column 9_y,Column 10_e,...,Column 13_y,Column 14_c,Column 15_c,Column 16_p,Column 17_w,Column 18_n,Column 19_n,Column 20_w,Column 21_c,Column 22_d
5643,Column 1_f,Column 2_y,Column 3_c,Column 4_f,Column 5_m,Column 6_a,Column 7_c,Column 8_b,Column 9_y,Column 10_e,...,Column 13_y,Column 14_c,Column 15_c,Column 16_p,Column 17_w,Column 18_n,Column 19_n,Column 20_w,Column 21_c,Column 22_d

In [25]:
new_df.columns

Index(['Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5', 'Column 6',
       'Column 7', 'Column 8', 'Column 9', 'Column 10', 'Column 11',
       'Column 12', 'Column 13', 'Column 14', 'Column 15', 'Column 16',
       'Column 17', 'Column 18', 'Column 19', 'Column 20', 'Column 21',
       'Column 22'],
      dtype='object')

In [26]:
def replace_column_values(dataframe):
    
    for col_name in dataframe.columns:
        data_list=dataframe[col_name]
        for index, data in enumerate(data_list):
            data=data.replace(col_name+'_','')
            data_list[index]=data
        dataframe[col_name]=data_list    
    return(dataframe)

In [27]:
mod_df=replace_column_values(new_df)
mod_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,f,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [28]:
mod_df.dtypes

Column 1     object
Column 2     object
Column 3     object
Column 4     object
Column 5     object
Column 6     object
Column 7     object
Column 8     object
Column 9     object
Column 10    object
Column 11    object
Column 12    object
Column 13    object
Column 14    object
Column 15    object
Column 16    object
Column 17    object
Column 18    object
Column 19    object
Column 20    object
Column 21    object
Column 22    object
dtype: object

calculating AE

In [29]:
copy_est_df=mod_df.astype('string')

In [30]:
m=copy_est_df.astype('string')
m

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,f,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [31]:
# I function
def I_function(copy_est_df,original_df):
    for col_name in copy_est_df.columns:
        #copy_est_df[col_name] = copy_est_df[col_name].astype('string')
        #original_df[col_name] = original_df[col_name].astype('string')
        est_data_list=copy_est_df[col_name].astype('string')
        #print(est_data_list.dtypes)
        org_data_list=original_df[col_name].astype('string')
        for index, data in enumerate(est_data_list):
            if est_data_list[index]==org_data_list[index]:
                est_data_list[index]='0'
            else:
                est_data_list[index]='1'
            
        copy_est_df[col_name]=est_data_list
    return(copy_est_df.astype('int64'))

In [32]:
def Sum_new(sum):
    summ=0
    for n in sum:
        summ=summ+n
    return (summ)

𝐴𝐸 = (1 /𝑛) ∑ 𝐼(𝑥̂𝑖 = 𝑥𝑖)

In [33]:
def AE(copy_est_df,original_df):
    copy_est_df=I_function(copy_est_df,original_df)
    total_sum=copy_est_df.astype('int64').sum()
    final_sum=Sum_new(total_sum)
    ae=final_sum/(5644*22)
    return(ae)

In [34]:
AE(copy_est_df,complete_df)

0.0030281554023580954

In [36]:
mod_df.to_excel("MUSH_AN_1(imp).xlsx", index=False,header=False)