In [9]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd
import tensorflow as tf
import MIDASpy as md

In [10]:
column_names=['Column 1','Column 2','Column 3','Column 4','Column 5','Column 6','Column 7','Column 8','Column 9','Column 10','Column 11','Column 12','Column 13','Column 14','Column 15','Column 16','Column 17','Column 18','Column 19','Column 20','Column 21','Column 22']
df=pd.read_excel(r'C:\Users\furqz\OneDrive\Desktop\Data mining stiff\incomplete\Incomplete Datasets Without Labels\MUSH\MUSH_AE_5.xlsx',header=None,names=column_names)
df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,NaN,n,f,w,b,k,t,...,NaN,NaN,NaN,p,w,o,NaN,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,NaN,n,f,c,b,w,e,...,NaN,NaN,NaN,p,w,t,NaN,w,y,p
5641,x,y,g,NaN,n,f,c,b,w,e,...,NaN,NaN,NaN,p,w,t,NaN,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [11]:
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [12]:
import tensorflow as tf
tf.compat.v1.reset_default_graph()

In [13]:
import tensorflow as tf
tf.compat.v1.reset_default_graph()

In [14]:
import tensorflow.compat.v1 as tf
tf.reset_default_graph()

In [15]:
categorical = ['Column 1','Column 2','Column 3','Column 4','Column 5','Column 6','Column 7','Column 8','Column 9','Column 10','Column 11','Column 12','Column 13','Column 14','Column 15','Column 16','Column 17','Column 18','Column 19','Column 20','Column 21','Column 22']
data_cat, cat_cols_list = md.cat_conv(df[categorical])

df.drop(categorical, axis = 1, inplace = True)
constructor_list = [df]
constructor_list.append(data_cat)
data_in = pd.concat(constructor_list, axis=1)

na_loc = data_in.isnull()
data_in[na_loc] = np.nan

In [16]:
print(data_in.head())

   Column 1_b  Column 1_c  Column 1_f  Column 1_k  Column 1_s  Column 1_x  \
0         0.0         0.0         0.0         0.0         0.0         1.0
1         0.0         0.0         0.0         0.0         0.0         1.0
2         1.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         1.0
4         0.0         0.0         0.0         0.0         0.0         1.0

   Column 2_f  Column 2_g  Column 2_s  Column 2_y  ...  Column 21_n  \
0         0.0         0.0         1.0         0.0  ...          0.0
1         0.0         0.0         1.0         0.0  ...          1.0
2         0.0         0.0         1.0         0.0  ...          1.0
3         0.0         0.0         0.0         1.0  ...          0.0
4         0.0         0.0         1.0         0.0  ...          0.0

   Column 21_s  Column 21_v  Column 21_y  Column 22_d  Column 22_g  \
0          1.0          0.0          0.0          0.0          0.0
1          0.0          0.0          0.0          0.0          1.0
2          0.0          0.0          0.0          0.0          0.0
3          1.0          0.0          0.0          0.0          0.0
4          0.0          0.0          0.0          0.0          1.0

   Column 22_l  Column 22_m  Column 22_p  Column 22_u
0          0.0          0.0          0.0          1.0
1          0.0          0.0          0.0          0.0
2          0.0          1.0          0.0          0.0
3          0.0          0.0          0.0          1.0
4          0.0          0.0          0.0          0.0

[5 rows x 98 columns]

In [17]:
imputer = md.Midas(layer_structure = [22,22+9,22+9+9,22+9+9+9,22+9+9,22+9,22], vae_layer = False, seed = 100, input_drop = 0.5)
imputer.build_model(data_in,softmax_columns = cat_cols_list)
imputer.train_model(training_epochs = 100)

Size index: [6, 4, 8, 2, 7, 2, 2, 2, 9, 2, 4, 4, 4, 7, 7, 1, 2, 3, 4, 6, 6, 6]

Computation graph constructed

Model initialised

Epoch: 0 , loss: 26.58075851202011
Epoch: 1 , loss: 20.712186509912666
Epoch: 2 , loss: 19.870705832134593
Epoch: 3 , loss: 19.55191706527363
Epoch: 4 , loss: 19.33241151679646
Epoch: 5 , loss: 19.157819065180693
Epoch: 6 , loss: 19.05076983841983
Epoch: 7 , loss: 18.967932533134114
Epoch: 8 , loss: 18.87176983464848
Epoch: 9 , loss: 18.76836351643909
Epoch: 10 , loss: 18.68536766008897
Epoch: 11 , loss: 18.597441692243923
Epoch: 12 , loss: 18.550830044529654
Epoch: 13 , loss: 18.4883975955573
Epoch: 14 , loss: 18.443549822677266
Epoch: 15 , loss: 18.3781157867475
Epoch: 16 , loss: 18.279570533470675
Epoch: 17 , loss: 18.189845296469603
Epoch: 18 , loss: 18.155304586345498
Epoch: 19 , loss: 18.093180629340086
Epoch: 20 , loss: 17.979218260808423
Epoch: 21 , loss: 17.98500890352509
Epoch: 22 , loss: 17.92260611870072
Epoch: 23 , loss: 17.86304397745566
Epoch: 24 , loss: 17.866180398247458
Epoch: 25 , loss: 17.81058472124013
Epoch: 26 , loss: 17.766851519996468
Epoch: 27 , loss: 17.727347154508937
Epoch: 28 , loss: 17.63519830324433
Epoch: 29 , loss: 17.6176361116496
Epoch: 30 , loss: 17.58540786125443
Epoch: 31 , loss: 17.567031887444582
Epoch: 32 , loss: 17.53752984512936
Epoch: 33 , loss: 17.53307963230393
Epoch: 34 , loss: 17.469634039835498
Epoch: 35 , loss: 17.401094325564124
Epoch: 36 , loss: 17.426220165057615
Epoch: 37 , loss: 17.502635037357155
Epoch: 38 , loss: 17.359135440804742
Epoch: 39 , loss: 17.31836327368563
Epoch: 40 , loss: 17.269610925154254
Epoch: 41 , loss: 17.226183384656906
Epoch: 42 , loss: 17.17945793812925
Epoch: 43 , loss: 17.14851852980527
Epoch: 44 , loss: 17.127262405373834
Epoch: 45 , loss: 17.064260255206715
Epoch: 46 , loss: 16.970438426191155
Epoch: 47 , loss: 16.865745173259214
Epoch: 48 , loss: 16.825178886001762
Epoch: 49 , loss: 16.590142450549386
Epoch: 50 , loss: 16.54025911742991
Epoch: 51 , loss: 16.39510382305492
Epoch: 52 , loss: 16.304385204206813
Epoch: 53 , loss: 16.221269469369542
Epoch: 54 , loss: 16.193908165801655
Epoch: 55 , loss: 16.195800816470925
Epoch: 56 , loss: 16.136018067598343
Epoch: 57 , loss: 16.115789156068455
Epoch: 58 , loss: 16.08281842145053
Epoch: 59 , loss: 16.03954058343714
Epoch: 60 , loss: 16.03331506523219
Epoch: 61 , loss: 16.008819455450233
Epoch: 62 , loss: 16.004824367436495
Epoch: 63 , loss: 16.08656829866496
Epoch: 64 , loss: 15.94358224218542
Epoch: 65 , loss: 15.962672981348904
Epoch: 66 , loss: 15.93528893048113
Epoch: 67 , loss: 15.945726657455618
Epoch: 68 , loss: 15.877051041884856
Epoch: 69 , loss: 15.937882781028748
Epoch: 70 , loss: 15.884030629288066
Epoch: 71 , loss: 15.914134415713223
Epoch: 72 , loss: 15.89755774357102
Epoch: 73 , loss: 15.886805306781422
Epoch: 74 , loss: 15.84343643892895
Epoch: 75 , loss: 15.887878799980337
Epoch: 76 , loss: 15.842564176429402
Epoch: 77 , loss: 15.929093477400867
Epoch: 78 , loss: 15.875617997212844
Epoch: 79 , loss: 15.80794957280159
Epoch: 80 , loss: 15.81128605929288
Epoch: 81 , loss: 15.825242625041442
Epoch: 82 , loss: 15.821299119429154
Epoch: 83 , loss: 15.870658592744308
Epoch: 84 , loss: 15.840510601347143
Epoch: 85 , loss: 15.816171705722809
Epoch: 86 , loss: 15.819575437090613
Epoch: 87 , loss: 15.815885421904651
Epoch: 88 , loss: 15.805193741213191
Epoch: 89 , loss: 15.724639811299063
Epoch: 90 , loss: 15.826112213459881
Epoch: 91 , loss: 15.77891354398294
Epoch: 92 , loss: 15.729767655784434
Epoch: 93 , loss: 15.709916366772218
Epoch: 94 , loss: 15.691270370375026
Epoch: 95 , loss: 15.740563094615936
Epoch: 96 , loss: 15.729714052243667
Epoch: 97 , loss: 15.66270204836672
Epoch: 98 , loss: 15.654192076487975
Epoch: 99 , loss: 15.577029371803457
Training complete. Saving file...
Model saved in file: tmp/MIDAS

In [18]:
imputations = imputer.generate_samples(m=10).output_list

INFO:tensorflow:Restoring parameters from tmp/MIDAS
Model restored.

In [19]:
np.shape(imputations[-1])

(5644, 98)

In [20]:
new_df=imputations[-1]

In [21]:
complete_df=pd.read_excel(r'C:\Users\furqz\OneDrive\Desktop\Data mining stiff\complete\Original Datasets Without Labels\MUSH.xlsx',header=None,names=column_names)
complete_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [22]:
flat_cats = [cat for variable in cat_cols_list for cat in variable]

for i in range(len(imputations)):
    tmp_cat = [imputations[i][x].idxmax(axis=1) for x in cat_cols_list]
    cat_df = pd.DataFrame({categorical[i]:tmp_cat[i] for i in range(len(categorical))})
    imputations[i] = pd.concat([imputations[i], cat_df], axis = 1).drop(flat_cats, axis = 1)

In [23]:
print(imputations[-1].columns)

Index(['Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5', 'Column 6',
       'Column 7', 'Column 8', 'Column 9', 'Column 10', 'Column 11',
       'Column 12', 'Column 13', 'Column 14', 'Column 15', 'Column 16',
       'Column 17', 'Column 18', 'Column 19', 'Column 20', 'Column 21',
       'Column 22'],
      dtype='object')

In [24]:
new_df=imputations[-1]
new_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,Column 1_x,Column 2_s,Column 3_n,Column 4_t,Column 5_p,Column 6_f,Column 7_c,Column 8_n,Column 9_k,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_k,Column 21_s,Column 22_u
1,Column 1_x,Column 2_s,Column 3_y,Column 4_t,Column 5_a,Column 6_f,Column 7_c,Column 8_b,Column 9_k,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_n,Column 21_n,Column 22_g
2,Column 1_b,Column 2_s,Column 3_w,Column 4_t,Column 5_l,Column 6_f,Column 7_c,Column 8_b,Column 9_n,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_n,Column 21_n,Column 22_m
3,Column 1_x,Column 2_y,Column 3_w,Column 4_t,Column 5_p,Column 6_f,Column 7_c,Column 8_n,Column 9_n,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_k,Column 21_s,Column 22_u
4,Column 1_x,Column 2_s,Column 3_g,Column 4_f,Column 5_n,Column 6_f,Column 7_w,Column 8_b,Column 9_k,Column 10_t,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_n,Column 21_a,Column 22_g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,Column 1_b,Column 2_y,Column 3_n,Column 4_f,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_y,Column 14_n,Column 15_n,Column 16_p,Column 17_w,Column 18_t,Column 19_p,Column 20_w,Column 21_y,Column 22_p
5640,Column 1_x,Column 2_y,Column 3_n,Column 4_t,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_t,Column 19_p,Column 20_w,Column 21_y,Column 22_p
5641,Column 1_x,Column 2_y,Column 3_g,Column 4_f,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_k,Column 14_w,Column 15_n,Column 16_p,Column 17_w,Column 18_t,Column 19_l,Column 20_w,Column 21_y,Column 22_p
5642,Column 1_x,Column 2_y,Column 3_c,Column 4_f,Column 5_m,Column 6_f,Column 7_c,Column 8_b,Column 9_y,Column 10_e,...,Column 13_y,Column 14_c,Column 15_c,Column 16_p,Column 17_w,Column 18_n,Column 19_n,Column 20_w,Column 21_c,Column 22_d
5643,Column 1_f,Column 2_y,Column 3_c,Column 4_f,Column 5_m,Column 6_a,Column 7_c,Column 8_b,Column 9_y,Column 10_e,...,Column 13_y,Column 14_c,Column 15_c,Column 16_p,Column 17_w,Column 18_n,Column 19_n,Column 20_w,Column 21_c,Column 22_d

In [25]:
new_df.columns

Index(['Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5', 'Column 6',
       'Column 7', 'Column 8', 'Column 9', 'Column 10', 'Column 11',
       'Column 12', 'Column 13', 'Column 14', 'Column 15', 'Column 16',
       'Column 17', 'Column 18', 'Column 19', 'Column 20', 'Column 21',
       'Column 22'],
      dtype='object')

In [26]:
def replace_column_values(dataframe):
    
    for col_name in dataframe.columns:
        data_list=dataframe[col_name]
        for index, data in enumerate(data_list):
            data=data.replace(col_name+'_','')
            data_list[index]=data
        dataframe[col_name]=data_list    
    return(dataframe)

In [27]:
mod_df=replace_column_values(new_df)
mod_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,p,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5641,x,y,g,f,n,f,c,b,w,e,...,k,w,n,p,w,t,l,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [28]:
mod_df.dtypes

Column 1     object
Column 2     object
Column 3     object
Column 4     object
Column 5     object
Column 6     object
Column 7     object
Column 8     object
Column 9     object
Column 10    object
Column 11    object
Column 12    object
Column 13    object
Column 14    object
Column 15    object
Column 16    object
Column 17    object
Column 18    object
Column 19    object
Column 20    object
Column 21    object
Column 22    object
dtype: object

calculating AE

In [29]:
copy_est_df=mod_df.astype('string')

In [30]:
m=copy_est_df.astype('string')
m

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,p,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5641,x,y,g,f,n,f,c,b,w,e,...,k,w,n,p,w,t,l,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [31]:
# I function
def I_function(copy_est_df,original_df):
    for col_name in copy_est_df.columns:
        #copy_est_df[col_name] = copy_est_df[col_name].astype('string')
        #original_df[col_name] = original_df[col_name].astype('string')
        est_data_list=copy_est_df[col_name].astype('string')
        #print(est_data_list.dtypes)
        org_data_list=original_df[col_name].astype('string')
        for index, data in enumerate(est_data_list):
            if est_data_list[index]==org_data_list[index]:
                est_data_list[index]='0'
            else:
                est_data_list[index]='1'
            
        copy_est_df[col_name]=est_data_list
    return(copy_est_df.astype('int64'))

In [32]:
def Sum_new(sum):
    summ=0
    for n in sum:
        summ=summ+n
    return (summ)

𝐴𝐸 = (1 /𝑛) ∑ 𝐼(𝑥̂𝑖 = 𝑥𝑖)

In [33]:
def AE(copy_est_df,original_df):
    copy_est_df=I_function(copy_est_df,original_df)
    total_sum=copy_est_df.astype('int64').sum()
    final_sum=Sum_new(total_sum)
    ae=final_sum/(5644*22)
    return(ae)

In [34]:
AE(copy_est_df,complete_df)

0.014834740029637266

In [35]:
mod_df.to_excel("MUSH_C_10(imp).xlsx", index=False,header=False)