In [27]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd
import tensorflow as tf
import MIDASpy as md

In [28]:
column_names=['Column 1','Column 2','Column 3','Column 4','Column 5','Column 6','Column 7','Column 8','Column 9','Column 10','Column 11','Column 12','Column 13','Column 14','Column 15','Column 16','Column 17','Column 18','Column 19','Column 20','Column 21','Column 22']
df=pd.read_excel(r'C:\Users\furqz\OneDrive\Desktop\Data mining stiff\incomplete\Incomplete Datasets Without Labels\MUSH\MUSH_C_1.xlsx',header=None,names=column_names)
df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,NaN,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [29]:
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [30]:
import tensorflow as tf
tf.compat.v1.reset_default_graph()

In [31]:
import tensorflow as tf
tf.compat.v1.reset_default_graph()

In [32]:
import tensorflow.compat.v1 as tf
tf.reset_default_graph()

In [33]:
categorical = ['Column 1','Column 2','Column 3','Column 4','Column 5','Column 6','Column 7','Column 8','Column 9','Column 10','Column 11','Column 12','Column 13','Column 14','Column 15','Column 16','Column 17','Column 18','Column 19','Column 20','Column 21','Column 22']
data_cat, cat_cols_list = md.cat_conv(df[categorical])

df.drop(categorical, axis = 1, inplace = True)
constructor_list = [df]
constructor_list.append(data_cat)
data_in = pd.concat(constructor_list, axis=1)

na_loc = data_in.isnull()
data_in[na_loc] = np.nan

In [34]:
print(data_in.head())

   Column 1_b  Column 1_c  Column 1_f  Column 1_k  Column 1_s  Column 1_x  \
0         0.0         0.0         0.0         0.0         0.0         1.0
1         0.0         0.0         0.0         0.0         0.0         1.0
2         1.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         1.0
4         0.0         0.0         0.0         0.0         0.0         1.0

   Column 2_f  Column 2_g  Column 2_s  Column 2_y  ...  Column 21_n  \
0         0.0         0.0         1.0         0.0  ...          0.0
1         0.0         0.0         1.0         0.0  ...          1.0
2         0.0         0.0         1.0         0.0  ...          1.0
3         0.0         0.0         0.0         1.0  ...          0.0
4         0.0         0.0         1.0         0.0  ...          0.0

   Column 21_s  Column 21_v  Column 21_y  Column 22_d  Column 22_g  \
0          1.0          0.0          0.0          0.0          0.0
1          0.0          0.0          0.0          0.0          1.0
2          0.0          0.0          0.0          0.0          0.0
3          1.0          0.0          0.0          0.0          0.0
4          0.0          0.0          0.0          0.0          1.0

   Column 22_l  Column 22_m  Column 22_p  Column 22_u
0          0.0          0.0          0.0          1.0
1          0.0          0.0          0.0          0.0
2          0.0          1.0          0.0          0.0
3          0.0          0.0          0.0          1.0
4          0.0          0.0          0.0          0.0

[5 rows x 98 columns]

In [35]:
imputer = md.Midas(layer_structure = [22,22+14,22+14+14,22+14+14+14,22+14+14,22+14,22], vae_layer = False, seed = 100, input_drop = 0.5)
imputer.build_model(data_in,softmax_columns = cat_cols_list)
imputer.train_model(training_epochs = 100)

Size index: [6, 4, 8, 2, 7, 2, 2, 2, 9, 2, 4, 4, 4, 7, 7, 1, 2, 3, 4, 6, 6, 6]

Computation graph constructed

Model initialised

Epoch: 0 , loss: 27.66326413371346
Epoch: 1 , loss: 21.515422523021698
Epoch: 2 , loss: 20.79048191959208
Epoch: 3 , loss: 20.468896567821503
Epoch: 4 , loss: 20.18605821241032
Epoch: 5 , loss: 20.01075493747538
Epoch: 6 , loss: 19.83449126373638
Epoch: 7 , loss: 19.749458648941733
Epoch: 8 , loss: 19.634382583878256
Epoch: 9 , loss: 19.48730969429016
Epoch: 10 , loss: 19.37013566493988
Epoch: 11 , loss: 19.25437596169385
Epoch: 12 , loss: 19.146728613159873
Epoch: 13 , loss: 19.094477631829
Epoch: 14 , loss: 18.893919746984135
Epoch: 15 , loss: 18.872462673620745
Epoch: 16 , loss: 18.759731728922237
Epoch: 17 , loss: 18.59546252814206
Epoch: 18 , loss: 18.543814734979108
Epoch: 19 , loss: 18.478470986539666
Epoch: 20 , loss: 18.370231568813324
Epoch: 21 , loss: 18.336345634677194
Epoch: 22 , loss: 18.35406097227877
Epoch: 23 , loss: 18.20996931195259
Epoch: 24 , loss: 18.20026709274812
Epoch: 25 , loss: 18.187466523864053
Epoch: 26 , loss: 18.10243541815064
Epoch: 27 , loss: 18.054801984266803
Epoch: 28 , loss: 17.926982557231728
Epoch: 29 , loss: 17.905081751671705
Epoch: 30 , loss: 17.76788666844368
Epoch: 31 , loss: 17.838685409589246
Epoch: 32 , loss: 17.653774933381513
Epoch: 33 , loss: 17.55527703057636
Epoch: 34 , loss: 17.435724968259986
Epoch: 35 , loss: 17.231842918829486
Epoch: 36 , loss: 17.05950066447258
Epoch: 37 , loss: 17.050149725242093
Epoch: 38 , loss: 16.877497691999782
Epoch: 39 , loss: 16.709102514115248
Epoch: 40 , loss: 16.715270611372862
Epoch: 41 , loss: 16.63205719806931
Epoch: 42 , loss: 16.56353546814485
Epoch: 43 , loss: 16.555718644098803
Epoch: 44 , loss: 16.52077133547176
Epoch: 45 , loss: 16.488417479124937
Epoch: 46 , loss: 16.41215148297223
Epoch: 47 , loss: 16.365912889892403
Epoch: 48 , loss: 16.379049824042752
Epoch: 49 , loss: 16.344627182592046
Epoch: 50 , loss: 16.416288234970786
Epoch: 51 , loss: 16.33699135075916
Epoch: 52 , loss: 16.312473261898216
Epoch: 53 , loss: 16.307839133522727
Epoch: 54 , loss: 16.29921985485337
Epoch: 55 , loss: 16.327330516143277
Epoch: 56 , loss: 16.365176631645724
Epoch: 57 , loss: 16.268398303877223
Epoch: 58 , loss: 16.33030760559169
Epoch: 59 , loss: 16.217105675827373
Epoch: 60 , loss: 16.325646476312116
Epoch: 61 , loss: 16.369990443641488
Epoch: 62 , loss: 16.29860752008178
Epoch: 63 , loss: 16.28711800141768
Epoch: 64 , loss: 16.224148839712143
Epoch: 65 , loss: 16.26465022022074
Epoch: 66 , loss: 16.211119413375854
Epoch: 67 , loss: 16.22421131079847
Epoch: 68 , loss: 16.21344795281237
Epoch: 69 , loss: 16.229138867421582
Epoch: 70 , loss: 16.199280681935225
Epoch: 71 , loss: 16.26014798608693
Epoch: 72 , loss: 16.213937640190125
Epoch: 73 , loss: 16.22645136984912
Epoch: 74 , loss: 16.211740745739505
Epoch: 75 , loss: 16.21932792121714
Epoch: 76 , loss: 16.1652677601034
Epoch: 77 , loss: 16.22374525666237
Epoch: 78 , loss: 16.235364480452105
Epoch: 79 , loss: 16.171806679530576
Epoch: 80 , loss: 16.199993751265787
Epoch: 81 , loss: 16.128404278646816
Epoch: 82 , loss: 16.185497254133224
Epoch: 83 , loss: 16.236690640449524
Epoch: 84 , loss: 16.124530564654957
Epoch: 85 , loss: 16.164594235745344
Epoch: 86 , loss: 16.166321768002078
Epoch: 87 , loss: 16.14861971681768
Epoch: 88 , loss: 16.136124426668342
Epoch: 89 , loss: 16.052072636105798
Epoch: 90 , loss: 16.072468616745688
Epoch: 91 , loss: 15.977564668113535
Epoch: 92 , loss: 15.906315340237184
Epoch: 93 , loss: 15.85071068460291
Epoch: 94 , loss: 15.834081189198928
Epoch: 95 , loss: 15.85145335576751
Epoch: 96 , loss: 15.797333511439236
Epoch: 97 , loss: 15.7250092652711
Epoch: 98 , loss: 15.794340962713415
Epoch: 99 , loss: 15.6537184715271
Training complete. Saving file...
Model saved in file: tmp/MIDAS

In [36]:
imputations = imputer.generate_samples(m=10).output_list

INFO:tensorflow:Restoring parameters from tmp/MIDAS
Model restored.

In [37]:
np.shape(imputations[-1])

(5644, 98)

In [38]:
new_df=imputations[-1]

In [39]:
complete_df=pd.read_excel(r'C:\Users\furqz\OneDrive\Desktop\Data mining stiff\complete\Original Datasets Without Labels\MUSH.xlsx',header=None,names=column_names)
complete_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [40]:
flat_cats = [cat for variable in cat_cols_list for cat in variable]

for i in range(len(imputations)):
    tmp_cat = [imputations[i][x].idxmax(axis=1) for x in cat_cols_list]
    cat_df = pd.DataFrame({categorical[i]:tmp_cat[i] for i in range(len(categorical))})
    imputations[i] = pd.concat([imputations[i], cat_df], axis = 1).drop(flat_cats, axis = 1)

In [41]:
print(imputations[-1].columns)

Index(['Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5', 'Column 6',
       'Column 7', 'Column 8', 'Column 9', 'Column 10', 'Column 11',
       'Column 12', 'Column 13', 'Column 14', 'Column 15', 'Column 16',
       'Column 17', 'Column 18', 'Column 19', 'Column 20', 'Column 21',
       'Column 22'],
      dtype='object')

In [42]:
new_df=imputations[-1]
new_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,Column 1_x,Column 2_s,Column 3_n,Column 4_t,Column 5_p,Column 6_f,Column 7_c,Column 8_n,Column 9_k,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_k,Column 21_s,Column 22_u
1,Column 1_x,Column 2_s,Column 3_y,Column 4_t,Column 5_a,Column 6_f,Column 7_c,Column 8_b,Column 9_k,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_n,Column 21_n,Column 22_g
2,Column 1_b,Column 2_s,Column 3_w,Column 4_t,Column 5_l,Column 6_f,Column 7_c,Column 8_b,Column 9_n,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_n,Column 21_n,Column 22_m
3,Column 1_x,Column 2_y,Column 3_w,Column 4_t,Column 5_p,Column 6_f,Column 7_c,Column 8_n,Column 9_n,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_p,Column 20_k,Column 21_s,Column 22_u
4,Column 1_x,Column 2_s,Column 3_g,Column 4_f,Column 5_n,Column 6_f,Column 7_w,Column 8_b,Column 9_k,Column 10_t,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_o,Column 19_e,Column 20_n,Column 21_a,Column 22_g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,Column 1_b,Column 2_y,Column 3_n,Column 4_f,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_y,Column 14_n,Column 15_n,Column 16_p,Column 17_w,Column 18_t,Column 19_p,Column 20_w,Column 21_y,Column 22_p
5640,Column 1_x,Column 2_y,Column 3_n,Column 4_f,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_y,Column 14_n,Column 15_n,Column 16_p,Column 17_w,Column 18_t,Column 19_p,Column 20_w,Column 21_y,Column 22_p
5641,Column 1_x,Column 2_y,Column 3_g,Column 4_t,Column 5_n,Column 6_f,Column 7_c,Column 8_b,Column 9_w,Column 10_e,...,Column 13_s,Column 14_w,Column 15_w,Column 16_p,Column 17_w,Column 18_t,Column 19_p,Column 20_w,Column 21_y,Column 22_p
5642,Column 1_x,Column 2_y,Column 3_c,Column 4_f,Column 5_m,Column 6_f,Column 7_c,Column 8_b,Column 9_y,Column 10_e,...,Column 13_y,Column 14_c,Column 15_c,Column 16_p,Column 17_w,Column 18_n,Column 19_n,Column 20_w,Column 21_c,Column 22_d
5643,Column 1_f,Column 2_y,Column 3_c,Column 4_f,Column 5_m,Column 6_a,Column 7_c,Column 8_b,Column 9_y,Column 10_e,...,Column 13_y,Column 14_c,Column 15_c,Column 16_p,Column 17_w,Column 18_n,Column 19_n,Column 20_w,Column 21_c,Column 22_d

In [43]:
new_df.columns

Index(['Column 1', 'Column 2', 'Column 3', 'Column 4', 'Column 5', 'Column 6',
       'Column 7', 'Column 8', 'Column 9', 'Column 10', 'Column 11',
       'Column 12', 'Column 13', 'Column 14', 'Column 15', 'Column 16',
       'Column 17', 'Column 18', 'Column 19', 'Column 20', 'Column 21',
       'Column 22'],
      dtype='object')

In [44]:
def replace_column_values(dataframe):
    
    for col_name in dataframe.columns:
        data_list=dataframe[col_name]
        for index, data in enumerate(data_list):
            data=data.replace(col_name+'_','')
            data_list[index]=data
        dataframe[col_name]=data_list    
    return(dataframe)

In [45]:
mod_df=replace_column_values(new_df)
mod_df

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [46]:
mod_df.dtypes

Column 1     object
Column 2     object
Column 3     object
Column 4     object
Column 5     object
Column 6     object
Column 7     object
Column 8     object
Column 9     object
Column 10    object
Column 11    object
Column 12    object
Column 13    object
Column 14    object
Column 15    object
Column 16    object
Column 17    object
Column 18    object
Column 19    object
Column 20    object
Column 21    object
Column 22    object
dtype: object

calculating AE

In [47]:
copy_est_df=mod_df.astype('string')

In [48]:
m=copy_est_df.astype('string')
m

,Column 1,Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,...,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22
0,x,s,n,t,p,f,c,n,k,e,...,s,w,w,p,w,o,p,k,s,u
1,x,s,y,t,a,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,g
2,b,s,w,t,l,f,c,b,n,e,...,s,w,w,p,w,o,p,n,n,m
3,x,y,w,t,p,f,c,n,n,e,...,s,w,w,p,w,o,p,k,s,u
4,x,s,g,f,n,f,w,b,k,t,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5639,b,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5640,x,y,n,f,n,f,c,b,w,e,...,y,n,n,p,w,t,p,w,y,p
5641,x,y,g,t,n,f,c,b,w,e,...,s,w,w,p,w,t,p,w,y,p
5642,x,y,c,f,m,f,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d
5643,f,y,c,f,m,a,c,b,y,e,...,y,c,c,p,w,n,n,w,c,d

In [49]:
# I function
def I_function(copy_est_df,original_df):
    for col_name in copy_est_df.columns:
        #copy_est_df[col_name] = copy_est_df[col_name].astype('string')
        #original_df[col_name] = original_df[col_name].astype('string')
        est_data_list=copy_est_df[col_name].astype('string')
        #print(est_data_list.dtypes)
        org_data_list=original_df[col_name].astype('string')
        for index, data in enumerate(est_data_list):
            if est_data_list[index]==org_data_list[index]:
                est_data_list[index]='0'
            else:
                est_data_list[index]='1'
            
        copy_est_df[col_name]=est_data_list
    return(copy_est_df.astype('int64'))

In [50]:
def Sum_new(sum):
    summ=0
    for n in sum:
        summ=summ+n
    return (summ)

𝐴𝐸 = (1 /𝑛) ∑ 𝐼(𝑥̂𝑖 = 𝑥𝑖)

In [51]:
def AE(copy_est_df,original_df):
    copy_est_df=I_function(copy_est_df,original_df)
    total_sum=copy_est_df.astype('int64').sum()
    final_sum=Sum_new(total_sum)
    ae=final_sum/(5644*22)
    return(ae)

In [52]:
AE(copy_est_df,complete_df)

0.003213388312608724

In [53]:
mod_df.to_excel("MUSH_C_1(imp).xlsx", index=False,header=False)