# Welcome to A Gentle Introduction to Keras

This course focuses on a specific sub-field of machine learning called **predictive modeling.**

Within predicitve modeling is a speciality or another sub-field called **deep learning.**

We will be crafting deep learning models with a library called Keras. 

>**Predictive modeling** is focused on developing models that make accurate predictions at the expense of explaining why predictions are made. 

You and I don't need to be able to write a binary classification model. We need to know how to use and interpret the results of the model.

**Where does machine learning fit into data science?**

Data science is a much broader discipline. 

> Data Scientists take the raw data, analyse it, connect the dots and tell a story often via several visualizations. They usually have a broader range of skill-set and may not have too much depth into more than one or two. They are more on the creative side. Like an Artist. An Engineer, on the other hand, is someone who looks at the data as something they have to take in and churn out an output in some appropriate form in the most efficient way possible. The implementation details and other efficiency hacks are usually on the tip of their fingers. There can be a lot of overlap between the two but it is more like A Data Scientist is a Machine Learning Engineer but not the other way round. -- Ria Chakraborty, Data Scientist

# Step 1. Import our modules

Two important points here. Firstly, the **from** means we aren't importing the entire library, only a specific module. Secondly, notice we **are** imporing the entire numpy library. 

> If you get a message that states: WARNING (theano.configdefaults): g++ not detected, blah... blah. Run this in your Anaconda prompt. 

conda install mingw libpython

In [56]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
import keras

# Step 2.  Set our random seed

Run an algorithm on a dataset and you've built a great model. Can you produce the same model again given the same data?
You should be able to. It should be a requirement that is high on the list for your modeling project.

> We achieve reproducibility in applied machine learning by using the exact same code, data and sequence of random numbers.

Random numbers are created using a random number generator. Itâ€™s a simple program that generates a sequence of numbers that are random enough for most applications.

This math function is deterministic. If it uses the same starting point called a seed number, it will give the same sequence of random numbers.

Hold on... what's **deterministic** mean? 

> "a deterministic algorithm is an algorithm which, given a particular input, will always produce the same output, with the underlying machine always passing through the same sequence of states"

Let's apply an English translator to this: 

> The **only purpose of seeding** is to make sure that you get the **exact same result** when you run this code many times on the exact same data.

In [57]:
#seed = 9
#numpy.random.seed(seed)

# Step 3.  Import our data set

Let's import the object called read_csv. 

We define a variable called filename and put our data set in it. 

The last line does the work. It using the function called **read_csv** to put the contents of our data set into a variable called dataframe.

In [58]:
from pandas import read_csv
filename = 'BBCN.csv'
dataframe = read_csv(filename)
dataframe

,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,EnglishEducation,HouseOwnerFlag,NumberCarsOwned,CommuteDistance,Region,Age,BikeBuyer
0,5,1,9.0,2,0,5,1,0,2,2,5,1
1,5,1,6.0,3,3,5,0,1,1,2,4,1
2,5,1,6.0,3,3,5,1,1,5,2,4,1
3,5,2,7.0,0,0,5,0,1,10,2,5,1
4,5,2,8.0,5,5,5,1,4,2,2,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...
495,3,1,4.0,2,2,3,1,1,2,3,5,0
496,3,1,4.0,2,2,3,1,2,1,3,5,1
497,3,2,4.0,2,2,3,1,2,2,3,5,0
498,3,1,4.0,3,3,3,1,2,2,1,4,0
499,3,1,4.0,3,3,3,1,2,2,1,4,0

# Step 4.  Split the Output Variables

The first thing we need to do is put our data in an array. 

> An array is a data structure that stores values of **same data type**. 

In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [59]:
array = dataframe.values

The code below is the trickest part of the exercise. Now, we are assinging X and y as output variables.

> That looks pretty easy but keep in mind that an array starts at 0. 

If you take a look at the shape of our dataframe (shape means the number of columns and rows) you can see we have 12 rows. 

On the X array below we saying... include all items in the array from 0 to 11. 

On the y array below we are saying... just use the column in the array mapped to the **11th row**. The **BikeBuyer** column. 

> Before we split X and Y out we are going to put them in an array.

In [60]:
X = array[:,0:11] 
X

array([[5., 1., 9., ..., 2., 2., 5.],
       [5., 1., 6., ..., 1., 2., 4.],
       [5., 1., 6., ..., 5., 2., 4.],
       ...,
       [3., 2., 4., ..., 2., 3., 5.],
       [3., 1., 4., ..., 2., 1., 4.],
       [3., 1., 4., ..., 2., 1., 4.]])

In [61]:
Y = array[:,11]
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 0.])

In [62]:
dataframe.head()

,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,EnglishEducation,HouseOwnerFlag,NumberCarsOwned,CommuteDistance,Region,Age,BikeBuyer
0,5,1,9.0,2,0,5,1,0,2,2,5,1
1,5,1,6.0,3,3,5,0,1,1,2,4,1
2,5,1,6.0,3,3,5,1,1,5,2,4,1
3,5,2,7.0,0,0,5,0,1,10,2,5,1
4,5,2,8.0,5,5,5,1,4,2,2,5,1

# Step 4.  Build the Model

We can piece it all together by adding each layer. 

> The first layer has 11 neurons and expects 11 input variables. 

The second hidden layer has 8 neurons.

The third hidden layer has 8 neurons. 

The output layer has 1 neuron to predict the class. 

How many hidden layers are in our model?

In [63]:
model = Sequential()
model.add(Dense(11, input_dim=11, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

C:\Users\Haidar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, input_dim=11, activation="relu", kernel_initializer="uniform")`

C:\Users\Haidar\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Haidar\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  after removing the cwd from sys.path.

# Step 5.  Compile the Model

A metric is a function that is used to judge the performance of your model. Metric functions are to be supplied in the  metrics parameter when a model is compiled.

>  Lastly, we set the cost (or loss) function to categorical_crossentropy. The (binary) cross-entropy is just the technical term for the **cost function** in logistic regression, and the categorical cross-entropy is its generalization for multi-class predictions via softmax

Binary learning models are models which just predict one of two outcomes: positive or negative. These models are very well suited to drive decisions, such as whether to administer a patient a certain drug or to include a lead in a targeted marketing campaign.

> Accuracy is perhaps the most intuitive performance measure. **It is simply the ratio of correctly predicted observations.**

Using accuracy is only good for symmetric data sets where the class distribution is 50/50 and the cost of false positives and false negatives are roughly the same. In our case our classes are balanced.

Whenever you train a model with your data, you are actually producing some new values (predicted) for a specific feature. However, that specific feature already has some values which are real values in the dataset. 

> We know the the closer the predicted values to their corresponding real values, the better the model.

We are using cost function to measure **how close the predicted values are to their corresponding real values.**

So, for our model we choose binary_crossentropy.

In [64]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Step 5.  Fit the Model

**Epoch:** A full pass over all of your training data.

For example, let's say you have 1213 observations. So an epoch concludes when it has finished a training pass over all 1213 of your observations.

> What you'd expect to see from running fit on your Keras model, is a decrease in loss over n number of epochs.

batch_size denotes the subset size of your training sample (e.g. 100 out of 1000) which is going to be used in order to train the network during its learning process. 

Each batch trains network in a successive order, taking into account the updated weights coming from the appliance of the previous batch. 

>Example: if you have 1000 training examples, and your batch size is 500, then it will take 2 iterations to complete 1 epoch.

In [65]:
model.fit(X, Y, epochs=30, callbacks=[keras.callbacks.EarlyStopping(patience=3)])

Epoch 1/30
500/500 [==============================] - 1s 2ms/step - loss: 0.6930 - acc: 0.5340
Epoch 2/30
500/500 [==============================] - 0s 144us/step - loss: 0.6927 - acc: 0.5340
Epoch 3/30
500/500 [==============================] - 0s 150us/step - loss: 0.6924 - acc: 0.5340
Epoch 4/30
 32/500 [>.............................] - ETA: 0s - loss: 0.6948 - acc: 0.4375

C:\Users\Haidar\Anaconda3\lib\site-packages\keras\callbacks.py:569: RuntimeWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,acc
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning

500/500 [==============================] - 0s 160us/step - loss: 0.6921 - acc: 0.5340
Epoch 5/30
500/500 [==============================] - 0s 168us/step - loss: 0.6920 - acc: 0.5340
Epoch 6/30
500/500 [==============================] - 0s 162us/step - loss: 0.6911 - acc: 0.5340
Epoch 7/30
500/500 [==============================] - 0s 162us/step - loss: 0.6907 - acc: 0.5380
Epoch 8/30
500/500 [==============================] - 0s 176us/step - loss: 0.6896 - acc: 0.5340
Epoch 9/30
500/500 [==============================] - 0s 148us/step - loss: 0.6888 - acc: 0.5500
Epoch 10/30
500/500 [==============================] - 0s 158us/step - loss: 0.6867 - acc: 0.5600
Epoch 11/30
500/500 [==============================] - 0s 160us/step - loss: 0.6845 - acc: 0.5700
Epoch 12/30
500/500 [==============================] - 0s 144us/step - loss: 0.6817 - acc: 0.5880
Epoch 13/30
500/500 [==============================] - 0s 156us/step - loss: 0.6784 - acc: 0.6000
Epoch 14/30
500/500 [==============================] - 0s 144us/step - loss: 0.6756 - acc: 0.6020
Epoch 15/30
500/500 [==============================] - 0s 142us/step - loss: 0.6719 - acc: 0.6080
Epoch 16/30
500/500 [==============================] - 0s 160us/step - loss: 0.6670 - acc: 0.6220
Epoch 17/30
500/500 [==============================] - 0s 160us/step - loss: 0.6630 - acc: 0.6180
Epoch 18/30
500/500 [==============================] - 0s 164us/step - loss: 0.6610 - acc: 0.6180
Epoch 19/30
500/500 [==============================] - 0s 178us/step - loss: 0.6566 - acc: 0.6340
Epoch 20/30
500/500 [==============================] - 0s 153us/step - loss: 0.6548 - acc: 0.6200
Epoch 21/30
500/500 [==============================] - 0s 166us/step - loss: 0.6523 - acc: 0.6160
Epoch 22/30
500/500 [==============================] - 0s 170us/step - loss: 0.6477 - acc: 0.6380
Epoch 23/30
500/500 [==============================] - 0s 170us/step - loss: 0.6501 - acc: 0.6300
Epoch 24/30
500/500 [==============================] - 0s 164us/step - loss: 0.6453 - acc: 0.6320
Epoch 25/30
500/500 [==============================] - 0s 182us/step - loss: 0.6421 - acc: 0.6360
Epoch 26/30
500/500 [==============================] - 0s 170us/step - loss: 0.6409 - acc: 0.6340
Epoch 27/30
500/500 [==============================] - 0s 148us/step - loss: 0.6415 - acc: 0.6300
Epoch 28/30
500/500 [==============================] - 0s 152us/step - loss: 0.6384 - acc: 0.6340
Epoch 29/30
500/500 [==============================] - 0s 148us/step - loss: 0.6397 - acc: 0.6320
Epoch 30/30
500/500 [==============================] - 0s 158us/step - loss: 0.6358 - acc: 0.6400

# Step 6.  Score the Model

In [66]:
scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

500/500 [==============================] - 0s 502us/step
acc: 64.00%

In [38]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_10 (Dense)             (None, 11)                132
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 12
=================================================================
Total params: 144
Trainable params: 144
Non-trainable params: 0
_________________________________________________________________

In [39]:
model.predict(X)

array([[0.6002093 ],
       [0.4867304 ],
       [0.4707555 ],
       [0.6683343 ],
       [0.3986563 ],
       [0.7092979 ],
       [0.66000223],
       [0.5198482 ],
       [0.3825883 ],
       [0.7156464 ],
       [0.6669218 ],
       [0.4784165 ],
       [0.5061534 ],
       [0.6046937 ],
       [0.49484262],
       [0.47828552],
       [0.5276639 ],
       [0.3713737 ],
       [0.5812557 ],
       [0.56073755],
       [0.57693785],
       [0.5054064 ],
       [0.5382372 ],
       [0.55460817],
       [0.5991019 ],
       [0.54016775],
       [0.60315186],
       [0.57970554],
       [0.53965443],
       [0.5957106 ],
       [0.48150355],
       [0.38541317],
       [0.38541317],
       [0.4245747 ],
       [0.36988884],
       [0.48150355],
       [0.5594947 ],
       [0.5168146 ],
       [0.4650374 ],
       [0.5204415 ],
       [0.58427423],
       [0.5594947 ],
       [0.571959  ],
       [0.60062975],
       [0.54912406],
       [0.51880664],
       [0.43771005],
       [0.46172246],
       [0.49455306],
       [0.5090722 ],
       [0.49455306],
       [0.51880664],
       [0.5414952 ],
       [0.56711805],
       [0.5337914 ],
       [0.5900191 ],
       [0.47392836],
       [0.6477908 ],
       [0.6456614 ],
       [0.57573533],
       [0.630407  ],
       [0.630407  ],
       [0.55466324],
       [0.49771455],
       [0.55466324],
       [0.5686801 ],
       [0.5552478 ],
       [0.60062975],
       [0.55025244],
       [0.57413477],
       [0.6059603 ],
       [0.55025244],
       [0.57413477],
       [0.53813714],
       [0.5942391 ],
       [0.5486766 ],
       [0.6044394 ],
       [0.5725776 ],
       [0.521963  ],
       [0.76798   ],
       [0.76798   ],
       [0.49273434],
       [0.6342788 ],
       [0.6270603 ],
       [0.5178734 ],
       [0.4109676 ],
       [0.40971708],
       [0.28930098],
       [0.4373104 ],
       [0.42134845],
       [0.48663408],
       [0.4763268 ],
       [0.4963103 ],
       [0.65359265],
       [0.6578958 ],
       [0.6338161 ],
       [0.64788234],
       [0.62390196],
       [0.5945433 ],
       [0.66747594],
       [0.5720457 ],
       [0.6832206 ],
       [0.39713132],
       [0.66000223],
       [0.7305243 ],
       [0.6669218 ],
       [0.7156464 ],
       [0.62743795],
       [0.71750706],
       [0.7614783 ],
       [0.62390196],
       [0.58705115],
       [0.58705115],
       [0.37095535],
       [0.29725718],
       [0.36414832],
       [0.34712046],
       [0.3171892 ],
       [0.6702115 ],
       [0.7105212 ],
       [0.5204438 ],
       [0.36864197],
       [0.38806027],
       [0.36864197],
       [0.64653295],
       [0.58241177],
       [0.53546566],
       [0.45694223],
       [0.45694223],
       [0.45694223],
       [0.4855073 ],
       [0.511828  ],
       [0.49325147],
       [0.52476   ],
       [0.35895818],
       [0.563032  ],
       [0.52243507],
       [0.49612325],
       [0.52243507],
       [0.5325163 ],
       [0.5645974 ],
       [0.52243507],
       [0.578952  ],
       [0.55466324],
       [0.578952  ],
       [0.52243507],
       [0.5610286 ],
       [0.6029972 ],
       [0.6163324 ],
       [0.6337472 ],
       [0.6163324 ],
       [0.5548504 ],
       [0.55466324],
       [0.49771455],
       [0.4827422 ],
       [0.5638161 ],
       [0.5069975 ],
       [0.49771455],
       [0.55466324],
       [0.521963  ],
       [0.54750746],
       [0.5069975 ],
       [0.5398189 ],
       [0.5398189 ],
       [0.5638161 ],
       [0.52820784],
       [0.5810792 ],
       [0.5768286 ],
       [0.6329296 ],
       [0.31269133],
       [0.26576066],
       [0.62082237],
       [0.5657097 ],
       [0.69393975],
       [0.5579818 ],
       [0.61077464],
       [0.3109195 ],
       [0.44267213],
       [0.5238479 ],
       [0.4266629 ],
       [0.5817885 ],
       [0.48505563],
       [0.33389342],
       [0.33389342],
       [0.33389342],
       [0.33389342],
       [0.33389342],
       [0.3132632 ],
       [0.35313597],
       [0.36441904],
       [0.3314335 ],
       [0.31715786],
       [0.40598845],
       [0.40598845],
       [0.35223114],
       [0.30803037],
       [0.35731497],
       [0.3688056 ],
       [0.2775349 ],
       [0.2775349 ],
       [0.35906684],
       [0.2775349 ],
       [0.32857388],
       [0.39659673],
       [0.37180603],
       [0.34336418],
       [0.40260482],
       [0.34903225],
       [0.3355447 ],
       [0.3355447 ],
       [0.338915  ],
       [0.37180603],
       [0.37180603],
       [0.3870383 ],
       [0.44247916],
       [0.35513616],
       [0.3870383 ],
       [0.3870383 ],
       [0.42435366],
       [0.4170959 ],
       [0.34903225],
       [0.31448615],
       [0.37148395],
       [0.4020242 ],
       [0.372642  ],
       [0.34903225],
       [0.37767363],
       [0.44247916],
       [0.3870383 ],
       [0.2833586 ],
       [0.30192137],
       [0.4170959 ],
       [0.34337735],
       [0.31770357],
       [0.27031645],
       [0.31770357],
       [0.26813638],
       [0.7924812 ],
       [0.75236654],
       [0.62483263],
       [0.7114355 ],
       [0.7114355 ],
       [0.70501804],
       [0.6927838 ],
       [0.72066396],
       [0.6731494 ],
       [0.62099934],
       [0.62438256],
       [0.6723569 ],
       [0.61858964],
       [0.5354734 ],
       [0.43985903],
       [0.5634255 ],
       [0.6354523 ],
       [0.51314545],
       [0.51155496],
       [0.4545152 ],
       [0.6953553 ],
       [0.74031067],
       [0.41124818],
       [0.49114338],
       [0.4646886 ],
       [0.24372047],
       [0.23718673],
       [0.29411685],
       [0.24321449],
       [0.54347265],
       [0.44365346],
       [0.44374543],
       [0.50273865],
       [0.54350764],
       [0.5929742 ],
       [0.20750108],
       [0.39244014],
       [0.60692626],
       [0.4835939 ],
       [0.28049958],
       [0.3361981 ],
       [0.57942873],
       [0.5151867 ],
       [0.57185847],
       [0.40306586],
       [0.3418654 ],
       [0.5493485 ],
       [0.49234217],
       [0.60532224],
       [0.7264905 ],
       [0.2837764 ],
       [0.52700144],
       [0.45681733],
       [0.52700144],
       [0.52700144],
       [0.5971047 ],
       [0.4852868 ],
       [0.4852868 ],
       [0.4383569 ],
       [0.54967856],
       [0.5099644 ],
       [0.52645564],
       [0.4097202 ],
       [0.30634418],
       [0.32064688],
       [0.36762437],
       [0.31624246],
       [0.43171862],
       [0.49023017],
       [0.49023017],
       [0.4952099 ],
       [0.4852868 ],
       [0.4050197 ],
       [0.39497054],
       [0.41838285],
       [0.39497054],
       [0.45071214],
       [0.41838285],
       [0.41838285],
       [0.440219  ],
       [0.36014986],
       [0.37550902],
       [0.3628991 ],
       [0.35037893],
       [0.3695436 ],
       [0.31802833],
       [0.48330438],
       [0.38506225],
       [0.3695436 ],
       [0.5790899 ],
       [0.3695436 ],
       [0.3695436 ],
       [0.3695436 ],
       [0.4127632 ],
       [0.27596217],
       [0.6292491 ],
       [0.6391038 ],
       [0.6412507 ],
       [0.6412507 ],
       [0.6900063 ],
       [0.69199634],
       [0.6900063 ],
       [0.6900063 ],
       [0.63516945],
       [0.695426  ],
       [0.47093675],
       [0.69470316],
       [0.6200895 ],
       [0.6200895 ],
       [0.60349685],
       [0.656724  ],
       [0.656724  ],
       [0.59556687],
       [0.6546219 ],
       [0.6567261 ],
       [0.6581576 ],
       [0.66623783],
       [0.6330069 ],
       [0.71311677],
       [0.64552164],
       [0.64552164],
       [0.5995928 ],
       [0.65304273],
       [0.6383985 ],
       [0.60651684],
       [0.6664912 ],
       [0.6664912 ],
       [0.44217417],
       [0.44829282],
       [0.587912  ],
       [0.6419902 ],
       [0.5052752 ],
       [0.5953993 ],
       [0.587912  ],
       [0.587912  ],
       [0.587912  ],
       [0.66623783],
       [0.71501976],
       [0.71501976],
       [0.71311677],
       [0.53397256],
       [0.6110182 ],
       [0.65684706],
       [0.66297626],
       [0.6042347 ],
       [0.657419  ],
       [0.5367289 ],
       [0.5495817 ],
       [0.6053131 ],
       [0.5495817 ],
       [0.54727346],
       [0.6030842 ],
       [0.66237605],
       [0.6095042 ],
       [0.4869492 ],
       [0.5440002 ],
       [0.5440002 ],
       [0.5440002 ],
       [0.7133837 ],
       [0.5916922 ],
       [0.7231825 ],
       [0.7577801 ],
       [0.6619781 ],
       [0.75606525],
       [0.7114742 ],
       [0.7114742 ],
       [0.7114742 ],
       [0.59262115],
       [0.59262115],
       [0.6057559 ],
       [0.66623574],
       [0.65552723],
       [0.52779675],
       [0.65146214],
       [0.625245  ],
       [0.47217703],
       [0.51085967],
       [0.5292828 ],
       [0.577688  ],
       [0.6700865 ],
       [0.44246957],
       [0.577688  ],
       [0.71787   ],
       [0.76104724],
       [0.66292727],
       [0.6228749 ],
       [0.51085967],
       [0.51302457],
       [0.49774736],
       [0.69475925],
       [0.5760795 ],
       [0.60115975],
       [0.59314793],
       [0.5217866 ],
       [0.51396275],
       [0.48713028],
       [0.52305394],
       [0.57445157],
       [0.6201517 ],
       [0.60467225],
       [0.617604  ],
       [0.55169415],
       [0.590077  ],
       [0.5732732 ],
       [0.5272294 ],
       [0.5557997 ],
       [0.7656041 ],
       [0.71254236],
       [0.7188481 ],
       [0.7188481 ],
       [0.7448404 ],
       [0.76475275],
       [0.76475275],
       [0.47895494],
       [0.7909967 ],
       [0.7273531 ],
       [0.77028245],
       [0.7273531 ],
       [0.59648925],
       [0.3943474 ],
       [0.72962546],
       [0.5404578 ],
       [0.7273531 ],
       [0.7777127 ],
       [0.7777127 ],
       [0.6214212 ],
       [0.62868416],
       [0.80079615],
       [0.80569386],
       [0.6848297 ],
       [0.6892885 ],
       [0.6465175 ],
       [0.77618825],
       [0.7848787 ],
       [0.71756124],
       [0.5253109 ],
       [0.740973  ],
       [0.77707696],
       [0.7515445 ],
       [0.6465175 ],
       [0.7527312 ],
       [0.7480916 ],
       [0.6968703 ],
       [0.6465175 ],
       [0.6465175 ],
       [0.70776623],
       [0.7318861 ],
       [0.60048735],
       [0.6063803 ],
       [0.7291455 ],
       [0.73522246],
       [0.77927446],
       [0.7434089 ],
       [0.7859515 ],
       [0.7859515 ],
       [0.74928933],
       [0.5425386 ],
       [0.5985048 ],
       [0.6370899 ],
       [0.67579854],
       [0.6218952 ],
       [0.3500758 ],
       [0.3500758 ]], dtype=float32)